apiVersion: flux.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: weave-scope
  namespace: scope
spec:
  releaseName: weave-scope
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: weave-scope
    version: 1.1.9
  values:
    image.pullPolicy: Always
